config/routes.rb
Rails.application.routes.draw do
  get 'bienvenidos/hello'
  devise_for :users
  root to: "posts#index"
  resources :posts
  resources :pages
  resources :bienvenidos
  # If you have a dedicated config/environments/staging.rb
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.staging?

  # If you use RAILS_ENV=production in staging environments, you'll need another
  # way to disable it in "real production"
  mount LetterOpenerWeb::Engine, at: "/letter_opener" unless ENV["PRODUCTION_FOR_REAL"]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/post.rb
class Post < ApplicationRecord
  has_rich_text :content
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bienvenidos_controller.rb
class BienvenidosController < ApplicationController
  def hello
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:show, :index] 
  # GET /services
  def index
    @posts = Post.all

    @q = Post.ransack(params[:q])
    @posts = @q.result
  end

  # GET /services/1
  def show
  end

  # GET /services/new
  def new
    @post = Post.new
  end

  # GET /services/1/edit
  def edit
  end

  # POST /services
  def create
    @post = Post.new(post_params)

    @post.user = current_user if current_user

    if @post.save
      redirect_to posts_path
      flash[:notice] = "Tu mini historia ha sido creada exitosamente."
    else
      flash[:notice] = "El no pudo ser creado."
      render :new
    end
  end

  # PATCH/PUT /services/1
  def update
    if @post.update(post_params)
      redirect_to post_path
      flash[:notice] = "Tu mini historia ha sido actualizada exitosamente."
    else
      render :edit
    end
  end

  def destroy
   @post.destroy
   redirect_to posts_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def post_params
      params.require(:post).permit(:title, :author, :content, :user_id)
    end
end

app/controllers/turbo_devise_user_controller.rb
class TurboDeviseUserController < ApplicationController
 class Responder < ActionController::Responder
    def to_turbo_stream
      controller.render(options.merge(formats: :html))
          rescue ActionView::MissingTemplate => error
      if get?
        raise error
      elsif has_errors? && default_action
        render rendering_options.merge(formats: :html, 
            status: :unprocessable_entity)
      else
        redirect_to navigation_location
      end
    end
  end

  self.responder = Responder
  respond_to :html, :turbo_stream
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bienvenidos_helper.rb
module BienvenidosHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/bienvenidos/index.html.erb
<div class="container">
 <div class="topnav">
  <% if user_signed_in?%>
    <a><%= link_to current_user.email, "#", class: "btn btn--primary" %></a>
    <a> <%= link_to 'Ingresa tu Mini Historia', new_post_path, class: "btn btn--primary" %></a>
    <a><%= link_to "Salir", destroy_user_session_path, class: "btn btn--primary", method: :delete %></a>
  <% else %>
    <a><%= link_to 'Volver', posts_path, class: "btn btn--primary" %></a>
  <% end %>
 </div>
<br>
<br>
<div class="card-product">
  <img src="https://res.cloudinary.com/aeyevenes/image/upload/v1632148717/Ale-4-MARCA_e3ko04.png" />
  <div class="card-product-infos">
   <h1>Bienvenidos</h1> 
    <p><strong>Bienvenido a la primera aplicación creada por mí mismo. Soy relativamente nuevo en el mundo de los rieles (Rails) y fue un desafío usar Rails 7.0.0 para crear una aplicación con Ruby 3.0.0; Devise, Editor de Texto Enriquecido y Ransack.
Esta aplicación fue creada para compartir historias cortas, puedes registrarte como autor y crear, actualizar y eliminar tus propias historias. Además, puedes buscar historias por su título o por tus autores favoritos.
Espero que puedas compartir con nosotros tu creatividad.
Para una mejor experiencia de usuario les recomiendo instalar LanguageTool.  
Alejandro Yévenes (aeyevenes@yahoo.com) </strong></p>
  </div>
</div>
<br>
<br>
<br>
<div class="card-product">
  <img src="https://res.cloudinary.com/aeyevenes/image/upload/v1632149579/Ale-2-MarcaAgua_humo_s2wwgq.gif" />
  <div class="card-product-infos">
   <h1>Welcome</h1> 
    <p><strong>Welcome to my first app built by myself. I am relative new in the rails word and was challenging to use Rails 7.0.0 and its new features to built and app with Ruby 3.0.0; Devise, Rich-Text Editor and Ransack.
This app was built to share short stories, you can register as an author and create, update and delete your own stories. Also, you can search for stories by their title or by your favorite authors.  
I hope you can share with us your creativity.
I recommend installing langugeTool for a better user experience.
Alejandro Yévenes (aeyevenes@yahoo.com)
 </strong></p>
  </div>
</div>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MiniHistorias_aeyevenes</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
  </head>

  <body>
    <%= yield %>
    <%= render 'shared/navbar' %>
  </body>
</html>

app/views/pages/index.html.erb
<h1> prueba de navbar en page </h1>

app/views/posts/_form.html.erb
<div class="form">
 <%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this   post from being saved:</h2>
      <ul>
        <% post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
  <div class="field">
    <%= form.label :author %>
    <%= form.text_field :author %>
  </div>
  <div class="field">
    <%= form.label :content %>
    <%= form.rich_text_area :content %>
  </div>
  <div class="actions">
    <%= form.submit %>
  </div>
 <% end %>
</div>

app/views/posts/_post.html.erb
<div id="<%= dom_id post %>">
  <p>
    <strong>Title:</strong>
    <%= post.title %>
  </p>

</div>

app/views/posts/edit.html.erb
<div class="container">
 <div class="topnav">
  <% if user_signed_in?%>
    <a><%= link_to current_user.email, "#", class: "btn btn--primary" %></a>
    <a> <%= link_to 'Ingresa tu Mini Historia', new_post_path, class: "btn btn--primary" %></a>
    <a><%= link_to "Salir", destroy_user_session_path, class: "btn btn--primary", method: :delete %></a>
  <% else %>
    <a><%= link_to "Ingreso Autor", new_user_session_path, class: "btn btn--primary" %></a>
    <a><%= link_to "Registro Nuevo Autor", new_user_registration_path, class: "btn btn--primary" %></a>
    <a><%= link_to 'Volver', posts_path, class: "btn btn--primary" %></a>
  <% end %>
 </div>
<br>
<br>
<div class="container">
 <h1>Editing post</h1>

 <%= render "form", post: @post %>

 <br>

 <div>
  <%= link_to "Ver mini historia", @post, class: "btn btn--primary" %> |
  <%= link_to "Volver", posts_path, class: "btn btn--primary" %>
 </div>
</div>

app/views/posts/index.html.erb
<div class="container">
 <div class="topnav">
  <% if user_signed_in?%>
    <a><%= link_to current_user.email, "#", class: "btn btn--primary" %></a>
    <a> <%= link_to 'Ingresa tu Mini Historia', new_post_path, class: "btn btn--primary" %></a>
    <a><%= link_to "Salir", destroy_user_session_path, class: "btn btn--primary", method: :delete %></a>
  <% else %>
    <a><%= link_to 'Bienvenidos / Welcome', bienvenidos_path, class: "btn btn--primary" %></a>
    <a><%= link_to "Ingreso Autor", new_user_session_path, class: "btn btn--primary" %></a>
    <a><%= link_to "Registro Nuevo Autor", new_user_registration_path, class: "btn btn--primary" %></a>
  <% end %>
 </div>
<br>
<br>
</div>
<div class="container">
 <div class="post">
  <h3 id="notice"><%= notice %></h3>
  <h1>Mini Historias</h1>
  <br>
  <%= search_form_for @q, remote: true do |f| %>
  <%= f.label :title_cont, 'Buscar en el Titulo' %>
  <%= f.search_field :title_cont %>
  <%= f.label :title_cont, 'Busca tu autor favorito' %>
  <%= f.search_field :author_cont %>
  <%= f.submit %>
<% end %>
<br>
  <table>
   <table width="100%" cellspacing="2px" style="border-spacing: 10px;">
   <thead>
     <tr>
       <th>Titulo</th>
       <th>Autor</th>
       <th colspan="3"></th>
     </tr>
   </thead>
   <tbody>
     <% @posts.each do |post| %>
       <tr>
         <td><%= post.title %></td>
         <td><%= post.author %></td>
         <td><%= link_to 'Ver', post, class: "btn btn--primary" %></td>
         <td> <% if current_user == post.user %>
          <%= link_to 'Editar', edit_post_path(post), class: "btn btn--primary" %>
          <%= link_to 'Borrar', post, data: { turbo_method: :delete }, class: "btn btn--primary" %>
         <% end %>
        </td>
       </tr>
     <% end %>
   </tbody>
  </table>
</div>

app/views/posts/new.html.erb
<div class="container">
 <div class="topnav">
  <% if user_signed_in?%>
    <a><%= link_to current_user.email, "#", class: "btn btn--primary" %></a>
    <a> <%= link_to 'Ingresa tu Mini Historia', new_post_path, class: "btn btn--primary" %></a>
    <a><%= link_to "Salir", destroy_user_session_path, class: "btn btn--primary", method: :delete %></a>
  <% else %>
    <a><%= link_to "Ingreso Autor", new_user_session_path, class: "btn btn--primary" %></a>
    <a><%= link_to "Registro Nuevo Autor", new_user_registration_path, class: "btn btn--primary" %></a>
    <%= link_to 'Ir a Home', posts_path, class: "btn btn--primary" %></a>
  <% end %>
 </div>
<div class="container">
  <h1>New post</h1>

  <%= render "form", post: @post %>

  <br>

  <div>
    <%= link_to "Regresa a tu cuenta", posts_path, class:"btn btn--primary" %>
  </div>
</div>

app/views/posts/show.html.erb
<div class="container">
 <div class="topnav">
  <% if user_signed_in?%>
    <a><%= link_to current_user.email, "#", class: "btn btn--primary" %></a>
    <a> <%= link_to 'Ingresa tu Mini Historia', new_post_path, class: "btn btn--primary" %></a>
    <a><%= link_to "Salir", destroy_user_session_path, class: "btn btn--primary", method: :delete %></a>
  <% else %>
    <a><%= link_to "Ingreso Autor", new_user_session_path, class: "btn btn--primary" %></a>
    <a><%= link_to "Registro Nuevo Autor", new_user_registration_path, class: "btn btn--primary" %></a>
    <a><%= link_to 'Volver', posts_path, class: "btn btn--primary" %></a>
  <% end %>
 </div>
<br>
<br>
<div class="container">
 <p id="notice"><%= notice %></p>
 <p>
  <strong>Title:</strong>
  <%= @post.title %>
 </p>
 <p>
  <strong>Autor:</strong>
  <%= @post.author %>
 </p>
 <p>
  <strong>Content:</strong>
  <%= @post.content %>
 </p>
 <% link_to 'Volver', posts_path, class: "btn btn--primary" %>
</div>